# Generated by Django 5.1.6 on 2025-02-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
    ]
